version: '3'

tasks:
  lint:
    desc: Run all linters
    cmds:
      - task --list-all | awk '{print $2}' | sed 's/:$//' | grep '^lint:' | xargs -I {} task {}

  fmt:
    desc: Run all formatters
    cmds:
      - task --list-all | awk '{print $2}' | sed 's/:$//' | grep '^fmt:' | xargs -I {} task {}

  ci:
    desc: Run CI checks
    deps:
      - lint
      - test

  test:
    desc: Run tests
    cmd: uv run pytest || [ $? -eq 5 ]

  lint:ruff:
    desc: Lint Python files
    cmd: ruff check . --fix

  fmt:ruff:
    desc: Format Python files
    cmd: ruff format .

  fmt:dprint:
    desc: Format files with dprint
    cmd: dprint fmt

  fmt:nix:
    desc: Format Nix files
    cmd: nixfmt *.nix
    ignore_error: true
